
INSERT INTO proyectofinal.producto (nom_prod, des_prod, val_prod, can_prod, img_prod, fab_prod) VALUES
('Bufanda de Lana Negra', 'Bufanda cálida y elegante para el invierno, en color negro sólido.', 25000.00, 50, 'img_bufanda_negra.jpg', 'Tejidos Artesanales'),
('Gorro Tejido Blanco', 'Gorro suave y cómodo en color blanco, ideal para climas fríos.', 18000.50, 45, 'img_gorro_blanco.jpeg', 'Creaciones Hilo'),
('Amigurumi Beige Oso', 'Oso de peluche amigurumi hecho a mano, en tono beige natural.', 35000.00, 20, 'img_amigurumi_beige.jpeg', 'Dulces Puntos'),
('Bolso Cruzado Verde', 'Bolso tejido a mano, estilo cruzado, en vibrante color verde esmeralda.', 45000.99, 30, 'img_bolso_verde.jpeg', 'Arte en Hilo'),
('Guantes de Invierno Azules', 'Guantes de punto gruesos y cálidos en azul marino, perfectos para el frío.', 20000.00, 60, 'img_guantes_azules.jpg', 'Manos Calientes'),
('Collar de Perlas Rojas', 'Elegante collar con cuentas rojas y detalles en hilo, ideal para eventos.', 29000.99, 25, 'img_collar_rojo.jpg', 'Accesorios Únicos'),
('Pulsera de Macramé Amarillo', 'Pulsera ajustable de macramé en alegre color amarillo, unisex.', 12000.50, 80, 'img_pulsera_amarilla.jpg', 'Nudos Creativos'),
('Bufanda de Cachemira Anaranjada', 'Bufanda de lujo en cachemira color anaranjado, muy suave al tacto.', 55000.00, 10, 'img_bufanda_naranja.jpg', 'Confort Supremo'),
('Gorro de Punto Rosado', 'Gorro de punto casual en un delicado tono rosado, con borla.', 19000.00, 40, 'img_gorro_rosado.jpeg', 'Estilo Púrpura'),
('Amigurumi de Gato Combinado', 'Amigurumi de gato con manchas combinadas de colores (blanco y negro).', 38000.00, 18, 'img_amigurumi_gato.jpeg', 'Mundo Amigurumi'),
('Bolso de Mano Negro Elegante', 'Bolso pequeño de mano tejido, ideal para fiestas, en color negro clásico.', 40000.00, 28, 'img_bolso_negro.jpeg', 'Tendencias Tejidas'),
('Guantes de Lana Blancos', 'Guantes finos de seda blanca, perfectos para ocasiones formales.', 28000.75, 35, 'img_guantes_blancos.jpg', 'Elegancia Textil'),
('Bufanda Cuadros Beige/Verde', 'Bufanda con patrón de cuadros en tonos beige y verde, moderna.', 30000.00, 22, 'img_bufanda_cuadros.jpeg', 'Diseños Únicos'),
('Gorro de Lino Azul', 'Gorro ligero de lino azul, ideal para primavera y verano.', 17000.00, 55, 'img_gorro_lino_azul.jpeg', 'Frescura Artesanal'),
('Amigurumi Dragón Rojo', 'Fiero pero adorable dragón amigurumi en color rojo vibrante.', 42000.00, 15, 'img_amigurumi_dragon.jpg', 'Criaturas Fantásticas'),
('Bolso de Compras Amarillo', 'Bolso grande de compras tejido en color amarillo brillante, ecológico.', 32000.00, 38, 'img_bolso_compras_amarillo.jpeg', 'EcoTejidos'),
('Guantes sin Dedos Anaranjados', 'Guantes sin dedos en punto grueso, color anaranjado, unisex.', 16000.00, 48, 'img_guantes_sin_dedos.jpg', 'Libertad Manos'),
('Collar de Cuentas Rosadas', 'Collar corto con cuentas de madera en tonos rosados, bohemio.', 24000.50, 27, 'img_collar_cuentas_rosadas.jpg', 'Joyas Boho'),
('Pulsera Trenzada Negra', 'Pulsera minimalista trenzada en hilo negro, ajustable.', 9000.00, 90, 'img_pulsera_negra.jpeg', 'Minimal Hilos'),
('Bufanda Estampado Azul/Blanco', 'Bufanda ligera con estampado azul y blanco, ideal para clima templado.', 27000.00, 33, 'img_bufanda_estampado.jpg', 'Viento Fresco'),
('Gorro de Ducha Beige', 'Gorro para la ducha de tela impermeable en color beige.', 10000.00, 70, 'img_gorro_ducha_beige.jpeg', 'Hogar Práctico'),
('Amigurumi Pulpo Verde', 'Tierno pulpo amigurumi en color verde pastel.', 30000.00, 25, 'img_amigurumi_pulpo.jpeg', 'Vida Marina Tejida'),
('Bolso de Playa Blanco', 'Bolso grande de playa tejido en blanco, con asas de cuerda.', 50000.00, 20, 'img_bolso_playa_blanco.jpg', 'Sol y Arena'),
('Guantes de Ciclismo Rojo', 'Guantes deportivos rojos con tejido transpirable y agarre mejorado.', 35000.00, 40, 'img_guantes_ciclismo.jpg', 'Ruta Segura'),
('Collar Étnico Amarillo', 'Collar largo étnico con colgantes de borlas amarillas.', 31000.00, 19, 'img_collar_etnico.jpeg', 'Tribal Chic'),
('Pulsera Hilos Combinados', 'Pulsera de hilos de varios colores combinados, estilo amistad.', 8.00, 100, 'img_pulsera_amistad.jpeg', 'Lazos Fuertes'),
('Bufanda Oversize Negra', 'Bufanda extra grande en color negro, ideal para un look casual.', 39.00, 12, 'img_bufanda_oversize.jpg', 'Moda Urbana'),
('Gorro Beanie Azul Marino', 'Gorro tipo beanie en azul marino, clásico y versátil.', 15.00, 65, 'img_gorro_beanie.jpg', 'Estilo Urbano'),
('Amigurumi Búho Rosado', 'Búho amigurumi de tamaño pequeño en tono rosado, con ojos grandes.', 28.00, 23, 'img_amigurumi_buho.jpg', 'Sabiduría Tejida'),
('Bolso Shopper Beige', 'Bolso tipo shopper tejido, práctico y espacioso para el día a día.', 48.00, 26, 'img_bolso_shopper.jpeg', 'Compras Inteligentes'),
('Guantes de Conducción Negros', 'Guantes de cuero negro para conducción, con detalles de punto.', 42.00, 18, 'img_guantes_conduccion.jpg', 'Ruta Elegante'),
('Bufanda de Seda Blanca', 'Bufanda de seda pura en blanco, ligera y suave, para primavera.', 60.00, 10, 'img_bufanda_seda_blanca.jpg', 'Lujo Ligero'),
('Gorro Pescador Verde', 'Gorro estilo pescador en tejido verde oliva, para protección solar.', 22.00, 30, 'img_gorro_pescador.jpeg', 'Aventura Verde'),
('Amigurumi Zorro Anaranjado', 'Amigurumi de zorro astuto en color anaranjado, con detalles blancos.', 37.00, 17, 'img_amigurumi_zorro.jpeg', 'Bosque Encantado'),
('Bolso Mochila Azul', 'Mochila tejida en color azul denim, cómoda y moderna.', 55.00, 24, 'img_mochila_azul.jpg', 'Aventura Urbana'),
('Guantes de Lana Combinados', 'Guantes de lana con patrón de colores combinados (gris, blanco, negro).', 21.00, 35, 'img_guantes_combinados.jpeg', 'Patrones Cálidos'),
('Collar de Cuentas Rojas y Negras', 'Collar con cuentas grandes en rojo y negro, estilo bold.', 27.00, 20, 'img_collar_rojo_negro.jpeg', 'Declaración Fuerte'),
('Pulsera de Abalorios Verdes', 'Pulsera elástica con pequeños abalorios verdes, sutil y elegante.', 10.00, 75, 'img_pulsera_verde.jpg', 'Toque Natural'),
('Bufanda Infinita Rosada', 'Bufanda circular infinita en tono rosado, versátil para cualquier atuendo.', 33.00, 28, 'img_bufanda_infinita.jpeg', 'Círculo de Estilo');